language: go
services:
  - mysql
  - redis
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

env:
  - GO111MODULE=on

dist: xenial

os:
  - linux

before_install:
  - go get -t -v ./...

before_script:
  - mysql -u root --password="" < .ci/tests.db.sql
script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)