language: go
services:
  - mysql
  - redis
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

env:
  - GO111MODULE=on

sudo: required

before_install:
  - go get ./...

before_script:
  - mysql -u root -e 'CREATE DATABASE test;'
  - mysql -u root -e "CREATE USER 'user'@'%' IDENTIFIED BY 'user';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'user'@'%';"

script:
  - go test -v ./...
