on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: run tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x,1.13.x,1.14.x,1.15.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.6'
      - name: Setting Up DB
        run: |
          mysql -h 127.0.0.1 -P 3306 --protocol=tcp -u root -padmin < .ci/tests.db.sql
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test -v -covermode=count ./...