on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    strategy:
      matrix:
        go-version: [1.12.x,1.13.x,1.14.x,1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    services:
      mysql:
        image: mysql:5.5
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name redis
    steps:
      - name: Verify MYSQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Setting Up DB
        run: |
        mysql -h mysql -P 3306 --protocol=tcp -u root -padmin < .ci/tests.db.sql
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -covermode=count ./...