on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: build
jobs:
  testing:
    strategy:
      matrix:
        go-version: [1.12.x,1.13.x,1.14.x,1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    services:
      mysql:
        image: mysql:5.5
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name redis
    steps:
      - name: Verify MYSQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting Up DB
        run: |
          mysql -h 127.0.0.1 -P 3306 --protocol=tcp -u root -padmin < .ci/tests.db.sql
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test -v -covermode=count ./...
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.5
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name redis
    steps:
      - name: Verify MYSQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
          done
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting Up DB
        run: |
          mysql -h 127.0.0.1 -P 3306 --protocol=tcp -u root -padmin < .ci/tests.db.sql
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
        id: go

      - name: Install gmct
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -v github.com/snail007/gmct/...@master
          go install github.com/snail007/gmct/cmd/gmct

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Generate coverage report
        env:
          GOPATH: $(go env GOPATH)
          PATH: $PATH:$GOPATH/bin
        run: |
#          export GOPATH=$(go env GOPATH)
#          export PATH=$PATH:$GOPATH/bin
          gmct cover -s -k
          pwd
          tree -d -L 2
#          go test `go list ./... |  grep -v main| grep -v examples | grep -v grep` -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: 4aba5ae6-8e6d-45f6-a049-d4517b562c28
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella